<b><h2>Linear Algebra (CpE210A)<h2><b>
    
    
<b><h3>Laboratory 8: System of Linear Equations<h3><b>
    
<h7>Coded and Submitted by:<h7>
    
<i><h7>Gonzales, James B.<h7><i>
    
<i><h7>58011<h7><i>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<b><h3>Exercise<h3><b>
    
<h7>1. Try to find your own example of a system of linear equations (minimum of 2 equations) and solve them using the inverse equation. Explain the details of your example.<h7>


$$ A = \left\{ \begin{array}\\ 2x+5y+2z=12\\ -5x-2y+2z=-5 \\ 7x+5y+5z=8 \end{array} \right. $$

In [6]:
x = np.array([
    [2,5,2],
    [-5,-2,2],
    [7,5,5]
])

y = np.array([
    [12],
    [-5],
    [8]
])

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)


x_inv = np.linalg.inv(x)
print("\nResult: ")
print(x_inv @ y)

Matrix x: 
 [[ 2  5  2]
 [-5 -2  2]
 [ 7  5  5]]

Matrix y: 
 [[12]
 [-5]
 [ 8]]

Result: 
[[-0.39849624]
 [ 2.82706767]
 [-0.66917293]]


<h7>2. Using your example in (1) solve it using np.linalg.solve(). Explain the function and its difference using the inverse equation.<h7>

In [5]:
x_inv1 = np.linalg.solve(x, y)

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)

print("\nResult: ")
print(x_inv1)

Matrix x: 
 [[ 2  5  2]
 [-5 -2  2]
 [ 7  5  5]]

Matrix y: 
 [[12]
 [-5]
 [ 8]]

Result: 
[[-0.39849624]
 [ 2.82706767]
 [-0.66917293]]
