<b><h2>Linear Algebra (CpE210A)<h2><b>
    
    
<b><h3>Laboratory 6: Matrices<h3><b>
    
<h7>Coded and Submitted by:<h7>
    
<i><h7>Gonzales, James B.<h7><i>
    
<i><h7>58011<h7><i>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<b><h3>Task 1<h3><b><br>

In [203]:
def mat_desc(x):
    print(x)
    if x.size > 0:
        is_square = True if x.shape[0] == x.shape[1] else False 
        print("Shape/Size: ", x.shape)
        print("Rank: ", x.ndim)
        print("Is an Square Matrix: ", is_square)
        is_zeros = not np.any(x)
        print("Is an Zero Matrix: ", is_zeros)
        is_ones = np.all((x == 1))
        print("Is an Ones Matrix: ", is_ones)
        #initialization of the length of rows and columns
        rows = len(x);  
        cols = len(x[0]);  
        is_identity=True
        #checking whether the diagonal is 1 and remaining values are 0 
        for i in range(0, rows):  
                for j in range(0, cols):  
                    if(i == j and x[i][j] != 1):  
                        is_identity = False
                    if(i != j and x[i][j] != 0):  
                        is_identity = False
        if is_identity:
            print("Is an Identity Matrix")
        else:
            print("Is not an Identity Matrix")
        print("Matrix is not Null")
    else:   
        print("Shape/Size: n/a")
        print("Rank: n/a")
        print("Is an Square Matrix: n/a")
        print("Is an Zero Matrix: n/a")
        print("Is an Ones Matrix: n/a")
        print("Is an Identity Matrix: n/a")
        print('Matrix is Null')  

In [204]:
A = np.array([[1,2,3],[1,3,5],[2,2,8]])
B = np.array([[0,0,0],[0,0,0],[0,0,0]])
C = np.array([[1,1,1],[1,1,1],[1,1,1]])
D = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])
E = np.array([])

In [205]:
mat_desc(A)

[[1 2 3]
 [1 3 5]
 [2 2 8]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is not an Identity Matrix
Matrix is not Null


In [206]:
mat_desc(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  True
Is an Ones Matrix:  False
Is not an Identity Matrix
Matrix is not Null


In [207]:
mat_desc(C)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  True
Is not an Identity Matrix
Matrix is not Null


In [208]:
mat_desc(D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape/Size:  (3, 3)
Rank:  2
Is an Square Matrix:  True
Is an Zero Matrix:  False
Is an Ones Matrix:  False
Is an Identity Matrix
Matrix is not Null


In [211]:
mat_desc(E)

[]
Shape/Size: n/a
Rank: n/a
Is an Square Matrix: n/a
Is an Zero Matrix: n/a
Is an Ones Matrix: n/a
Is an Identity Matrix: n/a
Matrix is Null


<b><h3>Task 2<h3><b><br>

In [67]:
def mat_operations(x,y):
    print("Array 1: \n", x)
    print("\nArray 2: \n", y)
    print("\nIs Scalar(Array1): ",isinstance(x, (int, float, complex, bytes)))
    print("\nIs Scalar(Array2): ",isinstance(y, (int, float, complex, bytes)))
    check_scalar1 = isinstance(x, (int, float, complex, bytes))
    check_scalar2 = isinstance(y, (int, float, complex, bytes))
    check_array1 = isinstance(x, np.ndarray)
    check_array2 = isinstance(y, np.ndarray)
    if check_scalar1 == True or check_scalar2 == True or check_array1 == True and check_array2 == True and x.shape == y.shape:
        print("\nSum of the two arrays: ")
        print(x+y)
        print("\nDifference of two arrays: ")
        print(x-y)
        print("\nProduct of the two arrays: ")
        print(x*y)
        print("\nQuotient of the two arrays: ")
        print(x/y)
    elif check_array1 == True and check_array2 == True and x.shape != y.shape:
        print("\nCan't perform certain operations, Shapes of array should be equal.")

In [73]:
F = 2
G = np.array([[1,1,2],[3,1,1],[1,8,4]])
H = np.array([[1,9,1],[1,3,2],[1,2,5]])
I = np.array([[9,8,7],[7,5,6],[8,3,2],[2,4,6]])
J = np.array([[5,1,1],[3,2,1],[2,6,8]])

In [65]:
 mat_operations(F,G)

Array 1: 
 2

Array 2: 
 [[1 1 2]
 [3 1 1]]

Is Scalar(Array1):  True

Is Scalar(Array2):  False

Sum of the two arrays: 
[[3 3 4]
 [5 3 3]]

Difference of two arrays: 
[[ 1  1  0]
 [-1  1  1]]

Product of the two arrays: 
[[2 2 4]
 [6 2 2]]

Quotient of the two arrays: 
[[2.         2.         1.        ]
 [0.66666667 2.         2.        ]]


In [70]:
 mat_operations(G,H)

Array 1: 
 [[1 1 2]
 [3 1 1]
 [1 8 4]]

Array 2: 
 [[1 9 1]
 [1 3 2]
 [1 2 5]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Sum of the two arrays: 
[[ 2 10  3]
 [ 4  4  3]
 [ 2 10  9]]

Difference of two arrays: 
[[ 0 -8  1]
 [ 2 -2 -1]
 [ 0  6 -1]]

Product of the two arrays: 
[[ 1  9  2]
 [ 3  3  2]
 [ 1 16 20]]

Quotient of the two arrays: 
[[1.         0.11111111 2.        ]
 [3.         0.33333333 0.5       ]
 [1.         4.         0.8       ]]


In [71]:
 mat_operations(H,I)

Array 1: 
 [[1 9 1]
 [1 3 2]
 [1 2 5]]

Array 2: 
 [[9 8 7]
 [7 5 6]
 [8 3 2]
 [2 4 6]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Can't perform certain operations, Shapes of array should be equal.


In [72]:
 mat_operations(I,J)

Array 1: 
 [[9 8 7]
 [7 5 6]
 [8 3 2]
 [2 4 6]]

Array 2: 
 [[5 1 1]
 [3 2 1]
 [2 6 8]]

Is Scalar(Array1):  False

Is Scalar(Array2):  False

Can't perform certain operations, Shapes of array should be equal.
