<b><h2>Linear Algebra (CpE210A)<h2><b>
    
    
<b><h3>Laboratory 7: Matrix Operations<h3><b>
    
<h7>Coded and Submitted by:<h7>
    
<i><h7>Gonzales, James B.<h7><i>
    
<i><h7>58011<h7><i>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<b><h3>Activity<h3><b><br>
<h4>Task 1<h4>
<h7>Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.<h7>

In [2]:
A = np.array([
    [5,1,2],
    [2,4,1],
    [2,1,2]
])

B = np.array([
    [3,1,1],
    [3,6,2],
    [1,2,4]
])

C = np.array([
    [4,1,3],
    [2,1,1],
    [1,5,1]
])
print("A = \n", A)
print("B = \n", B)
print("C = \n", C)

A = 
 [[5 1 2]
 [2 4 1]
 [2 1 2]]
B = 
 [[3 1 1]
 [3 6 2]
 [1 2 4]]
C = 
 [[4 1 3]
 [2 1 1]
 [1 5 1]]


$$A \cdot B \neq B \cdot A$$

In [3]:
print("A@B = \n", A @ B)
print("\nB@A = \n", B @ A)
np.array_equiv(A @ B, B @ A)

A@B = 
 [[20 15 15]
 [19 28 14]
 [11 12 12]]

B@A = 
 [[19  8  9]
 [31 29 16]
 [17 13 12]]


False

$$A \cdot (B \cdot C) = (A \cdot B) \cdot C$$

In [4]:
print("A@(B@C) = \n", (A @ (B@C)))
print("\n(A@B)@C = \n", ((A@B) @ C))
np.array_equiv( (A @ (B@C)), ((A@B) @ C))

A@(B@C) = 
 [[125 110  90]
 [146 117  99]
 [ 80  83  57]]

(A@B)@C = 
 [[125 110  90]
 [146 117  99]
 [ 80  83  57]]


True

$$A \cdot (B + C) = (A \cdot B) + (A \cdot C)$$

In [5]:
print("A@(B+C) = \n", (A @ (B+C)))
print("\n(A@B)+(A@C) = \n", ((A@B) + (A@C)))
np.array_equiv( (A @ (B+C)), ((A@B) + (A@C)))

A@(B+C) = 
 [[44 31 33]
 [36 39 25]
 [23 25 21]]

(A@B)+(A@C) = 
 [[44 31 33]
 [36 39 25]
 [23 25 21]]


True

$$(B + C) \cdot A = (B \cdot A) + (C \cdot A)$$

In [6]:
print("(B+C)@A = \n", ((B+C) @ A))
print("(B@A)+(C@A) = \n", ((B@A) + (C@A)))
np.array_equiv( ((B+C) @ A), ((B@A) + (C@A)))

(B+C)@A = 
 [[47 19 24]
 [45 36 23]
 [34 35 21]]
(B@A)+(C@A) = 
 [[47 19 24]
 [45 36 23]
 [34 35 21]]


True

$$A \cdot I = A$$

In [7]:
I = np.eye(3, dtype=int)
print("A@I = \n", A @ I)
print("\nA = \n", A)
np.array_equiv((A @ I), A)

A@I = 
 [[5 1 2]
 [2 4 1]
 [2 1 2]]

A = 
 [[5 1 2]
 [2 4 1]
 [2 1 2]]


True

$$A \cdot \emptyset = \emptyset$$

In [8]:
Zero_Amat = np.zeros(A.shape)
A_zero = A @ np.zeros(A.shape)

print("A @ \emptyset =")
print(A_zero)

print("\nEmpty set/matrix =")
print(Zero_Amat)

np.array_equal(A_zero, Zero_Amat)

A @ \emptyset =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Empty set/matrix =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

$$A \cdot A^{-1} = I$$

In [41]:
eq1 = A @ np.linalg.inv(A)
print("A@inverse of A= \n", eq1.astype(int))
print("\nI= \n", np.eye(3, dtype=int))

np.array_equal(eq1.astype(int), np.eye(3, dtype=int))

A@inverse of A= 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

I= 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


True